# default config file.
[server]
port = 7008

[database]
username = "btnuser"
password = "btn123"
dbName = "btndb?charset=utf8&parseTime=true"

[sms]
accountSID = "AC21b7beef6dcc64ba200ac17e4b5f00b4"
authToken = "3bd1d774aca57afc183d2ee5dfd174b9"
fromNumber = "+12016270931"
